// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqE2wK4U-xOQVajO-C0IkzZb5qn7rBqs',
    appId: '1:468748241635:web:40f28631c5e1b7a3c613d6',
    messagingSenderId: '468748241635',
    projectId: 'chat-app-4514b',
    authDomain: 'chat-app-4514b.firebaseapp.com',
    storageBucket: 'chat-app-4514b.appspot.com',
    measurementId: 'G-3T36EZHTXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOauODiWSlB0K_7a8Dzvs77BwOCho1dGE',
    appId: '1:468748241635:android:4b98267191ececddc613d6',
    messagingSenderId: '468748241635',
    projectId: 'chat-app-4514b',
    storageBucket: 'chat-app-4514b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNU9x2zSdDq-mryy03MM08Tpuxomjxyo',
    appId: '1:468748241635:ios:ffe91afe466e9f3dc613d6',
    messagingSenderId: '468748241635',
    projectId: 'chat-app-4514b',
    storageBucket: 'chat-app-4514b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTNU9x2zSdDq-mryy03MM08Tpuxomjxyo',
    appId: '1:468748241635:ios:f536b3767ca93377c613d6',
    messagingSenderId: '468748241635',
    projectId: 'chat-app-4514b',
    storageBucket: 'chat-app-4514b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
